// <auto-generated />
namespace ProvaBackEnd_07_17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Incial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Incial));
        
        string IMigrationMetadata.Id
        {
            get { return "201707312024036_Incial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
